#!/usr/bin/env bash
app-config memcache "
host = 127.0.0.1
port = 11211
persistent = 1
compression = true
binary_protocol = true
connect_timeout = 50
retry_timeout = 50
send_timeout = 50
recv_timeout = 50
poll_timeout = 50
key_prefix = '%PROJECT%:'
"
