#!/bin/bash
mysql_db=$PROJECT
mysql_ip='127.0.0.1'
mysql_port=$(allocate_port mysql)
mysql_password=$(</dev/urandom tr -dc A-Za-z0-9 | head -c40)
mysql_config=$CONFIG_DIR'/mariadb.cnf'  

app_config mysql "
innodb_buffer_pool_size = '64M'
shard[0] = 'mysql:host=$mysql_ip;port=$mysql_port;dbname=$mysql_db;user=root;password=$mysql_password'
"

php-exec "App::reconfigure()"

mkdir $VAR_DIR'/mariadb' 
mysql_install_db --defaults-file=$mysql_config > /dev/null
mysqld_safe --defaults-file=$mysql_config --nowatch > /dev/null
sleep 5
echo 'Mysql root password: '$mysql_password 
mysqladmin --defaults-file=$mysql_config -u root password "$mysql_password" 
echo '#!/bin/bash' > "$PROJECT_DIR/connect-db" 
echo 'mysql --defaults-file='$mysql_config' -u root -p"'$mysql_password'" '$mysql_db >> "$PROJECT_DIR/connect-db" 
chmod 0700 "$PROJECT_DIR/connect-db" 
mysql --defaults-file=$mysql_config -u root -p"$mysql_password" --silent -e 'CREATE DATABASE '$mysql_db 
pgrep -f "/usr/sbin/mysqld --defaults-file=$mysql_config" | xargs kill -TERM 
$PROJECT_DIR/task add 'mysqld_safe --defaults-file=$CONFIG_DIR/mariadb.cnf #mysql'